### ISSUE TITLE
Time Zone of Laravel APP not being used

### ISSUE THREAD

**Issue by sergiog95** [joaorbrandao/laravel-intervals#12]
Bug Description

The issue is that, when Carbon is being used in the laravel-intervals configuration files, the Carbon instance being used doesn't reflect the Time Zone defined for the Laravel APP.

This seems to be related to the way Laravel [loads configuration files](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php). They are loaded before a default Time Zone is set.

1. Set Laravel APP Time Zone to "Europe/Lisbon"
2. Call now() within the application and compare to a value where now() is being set in the larave-intervals config 
3. Compare both values

Expected behavior
Both now() and the now() set in the config of laravel-intervals should be equal.

**Screenshots**

Environment (please complete the following information):
 - Windows 10
 - Firefox
 - Laravel 7

**Comment by joaorbrandao** [comment]
Thank you for your feedback @sergiog95 ! You're right, this is related to Laravel caching the config files when `php artisan config:cache` is run.
I'll fix this and get back to you asap.
